Clase 1 y 4 ejercicios desafio
mariaelisaaraya/tareasIngeniasAlumnas pull request #14
Opened 2024-05-06 21:39 UTC by Junixza

> [!IMPORTANT]
> Checklist de entrega. Por favor, asegúrate de seguir cada uno de estos pasos cuidadosamente antes de realizar tu pull request.

## Lista de control para el Pull Request (PR):
- [ ] **Ubicación del PR**: Confirmo que he colocado mi pull request en la carpeta correspondiente al módulo y tarea específica.
- [ ] **Número de tarea**: He especificado claramente el número de la tarea que este PR resuelve.
- [ ] **Pruebas locales**: He realizado pruebas locales de mis cambios para asegurar que todo funciona como se espera.
- [ ] **Comentarios en el código**: He comentado mi código, especialmente en las áreas que podrían ser difíciles de entender para otros.
- [ ] **Control de errores**: Mis cambios no generan nuevas advertencias ni errores de compilación.

## Otros comentarios
Por favor, añade aquí cualquier otro comentario o contexto adicional sobre tu pull request. Esto podría incluir dificultades encontradas, decisiones de diseño importantes y referencias a discusiones relevantes.

2024-05-07 19:46 UTC, mariaelisaaraya commented
Bella necesataría que pongas el nombre correspondiente a los archivos. Corrobora como estan realizadas las tareas de las alumnas en las carpetas 04 y 05: 
https://github.com/mariaelisaaraya/tareasIngeniasAlumnas/tree/master/Modulo1/04Clase
https://github.com/mariaelisaaraya/tareasIngeniasAlumnas/tree/master/Modulo1/05Clase

Está aclarado en el PR los pasos correspondientes.

2024-05-08 04:32 UTC, Junixza commented
Hola Señorita, ahí los modifique, no había leído nada donde me hablará de los nombres de los archivos, espero que este bien ahora, cualquier cosa estoy pendiente, saludos!

2024-05-08 13:17 UTC, mariaelisaaraya commented on Modulo1/01Clase/paises.js
Recomendación de comentarios:
// Array de países
// Función para listar países
// Invocar la función

Agregar númeración de la tarea en comentarios: 
//1
//2
//3

Cambiar nombre de la carpeta como fue pedido:
01Clase/nombreAlumna/paises.js

2024-05-08 13:20 UTC, mariaelisaaraya commented on Modulo1/04Clase/servWeb.js
Cambiar nombre de la carpeta como fue pedido:
04Clase/nombreAlumna/archivos.

Sacar archivos duplicados.

2024-05-08 13:21 UTC, mariaelisaaraya commented on Modulo1/05Clase/project/server.js
Creo que este es un archivo duplicado.
Por favor corroborar el orden de los archivos que son entregados.

2024-05-09 02:14 UTC, mariaelisaaraya requested changes

2024-05-09 02:14 UTC, mariaelisaaraya commented on Modulo1/05Clase/yaidnyBriceno/server.js
Reordenar archivos y corroborar que se está subiendo.

2024-05-22 21:50 UTC, closed without merging