Feat: Adding my exercise from class 5
mariaelisaaraya/tareasIngeniasAlumnas pull request #15
Opened 2024-05-07 00:02 UTC by dxniela

> [!IMPORTANT]
> Checklist de entrega. Por favor, asegúrate de seguir cada uno de estos pasos cuidadosamente antes de realizar tu pull request.

## Lista de control para el Pull Request (PR):
- [ ] **Ubicación del PR**: Confirmo que he colocado mi pull request en la carpeta correspondiente al módulo y tarea específica.
- [ ] **Número de tarea**: He especificado claramente el número de la tarea que este PR resuelve.
- [ ] **Pruebas locales**: He realizado pruebas locales de mis cambios para asegurar que todo funciona como se espera.
- [ ] **Comentarios en el código**: He comentado mi código, especialmente en las áreas que podrían ser difíciles de entender para otros.
- [ ] **Control de errores**: Mis cambios no generan nuevas advertencias ni errores de compilación.

## Otros comentarios
Por favor, añade aquí cualquier otro comentario o contexto adicional sobre tu pull request. Esto podría incluir dificultades encontradas, decisiones de diseño importantes y referencias a discusiones relevantes.

2024-05-07 20:26 UTC, mariaelisaaraya commented on Modulo1/05Clase/ejercicioDanielaRamirez/index.js
Hola Dani ¡Gracias por enviar tu tarea! He revisado tu implementación del servidor web y todo parece estar funcionando muy bien pero lo que observo es que hay un pequeño ajuste que necesitamos hacer para alinear completamente tu trabajo con los requisitos de la tarea. Estan muy bien el manejo de las rutas inexistentes pero según las especificaciones de la tarea la respuesta para estas rutas debe ser en formato TEXTO PLANO. Actualmente, estás enviando la respuesta en formato JSON. Para corregir esto, te sugiero revisar cómo estás configurando el Content-Type y el método que usas para enviar la respuesta en tus rutas inexistentes. Piensa en cómo podrías modificar estos para cumplir con el requisito de enviar texto plano en lugar de JSON.

Espero las correcciones.

Lisa

2024-05-07 20:33 UTC, mariaelisaaraya commented on Modulo1/05Clase/ejercicioDanielaRamirez/package.json
Sobre tu archivo package.json noté que estás utilizando "node --watch index.js" en tu script de inicio, recorda que tocamos este tema brevemente en nuestra última clase, donde mencionamos que --watch es una característica experimental en Node.js a partir de la versión 18, y que para versiones anteriores, herramientas como nodemon son las recomendadas para monitorear cambios en los archivos automáticamente. Esto lo menciono porque cuando empiecen a trabajar en grupos lo tengan en cuenta.

2024-05-08 13:23 UTC, mariaelisaaraya requested changes
Pedido de corrección

2024-05-08 23:35 UTC, dxniela commented on Modulo1/05Clase/ejercicioDanielaRamirez/package.json
Vale, vale, gracias

2024-05-08 23:37 UTC, dxniela commented on Modulo1/05Clase/ejercicioDanielaRamirez/index.js
Gracias, ya lo acomodé. Me confundí porque en el enunciado piden que se mande una respuesta como texto plano pero también piden mandar un JSON como respuesta a las rutas inexistentes, igual cualquier otra corrección estoy pendiente

2024-05-09 02:16 UTC, merged